apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ui
  name: ui
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    app: ui
status:
  loadBalancer: {}
